### ISSUE TITLE
Default behaviour: load config.ini

### ISSUE THREAD

**Issue by g105b** [PhpGt/Config#2]
By default, this package should look for a `config.ini` in the project's root directory and load the contents into environment variables.

There are things to consider for this though:
- Where is the project's root directory? 
- Is it always going to be document root? 
- No - that's probably the `www` directory.
- So, should this package look up the directory tree from the doc root _until_ it finds a config.ini?
- Can `getcwd()` be used? Maybe PHP.Gt webengine could set the working directory to the project root, and so could other projects... so the expected behaviour is to load _only_ from the cwd?

**Comment by g105b** [comment]
Final bit handled in #13

**Comment by j4m3s** [comment]
FWIW:  Convention over configuration. Specify a location that will automatically be checked for the config file(s), and if someone wants to use this library they should put the config files there!   Strictly speaking, on Debian, that location is /etc/xyz - but for people using shared hosting that might not be an option.  I'd say a peer of the composer vendor directory, called config, is probably the most logical home.  Certainly not in the doc root or www directory!

**Comment by g105b** [comment]
Aye, good point. I'll reopen because I totally agree this can't be implied. Forcing default is a good call.

**Comment by j4m3s** [comment]
I'm going to change my suggestion on this one. Rather than putting the file in a config directory, put it in the project root. That's where all of the other config files like composer.json or bower.json go by default, so why not the same for gt.json :)
